name: myenv
channels:
- bioconda
- conda-forge
- defaults
- salilab
dependencies:
- python=3.8
- pandas
- scikit-learn
- dash
- biopython
- bioconductor-difflogo
- bioconductor-biostrings
- dssp
- scipy
- numpy
